version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: gameonton-redis
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NAME=${REDIS_NAME}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
volumes:
  mysql:
